spring:
  application:
    name: spring security oauth2
  profiles:
    active: local
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth_login_tutorial?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: ENC(JQfH5Ckmyq0BwPSylv5o+DUGcqfGgBB+)
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  # JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
# Security OAuth
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC(DNf1SeHYTxyyG9dJTGwSVAN8E3kXBTJUwD7nY2S7Ak8=)
            client-secret: ENC(+gIL8lfla1khvDTeN5iNH2/JeovNx6F2)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
#          google:
#            client-id: { client-id }
#            client-secret: { secret }
#            scope:
#               - profile
#               - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
# cors
app:
  cors:
    allowed-origins: 'http://localhost:3000'
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: '*'
    max-age: 3600
  # jwt secret key
  jwt:
    tokenSecret: ENC(ue4i7O795mbBVZEgETESWrl9m5L/Mw+rhsYEejK1MfyGb3Hkatdfpnb2vTLy+bYC)
    tokenExpiry: 600000
    refreshTokenExpiry: 7776000000

  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
