spring:
  application:
    name: spring security oauth2
  profiles:
    active: local
    include: [ config ]
  # DB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  # redis
  redis:
    host: localhost
    port: 6379
  # Security
  security:
    # URI ignore or permit-all
    patterns:
      permitAll: [ "/token/**", "/login/**", "/signup/**" ]
      member:
        GET: [ "/api/user/**" ]
        POST: [ ]
        PATCH: [ ]
        PUT: [ ]
        DELETE: [ ]
      admin:
        GET: [ ]
        POST: [ ]
        PATCH: [ ]
        PUT: [ ]
        DELETE: [ ]
    # Security OAuth
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC(DNf1SeHYTxyyG9dJTGwSVAN8E3kXBTJUwD7nY2S7Ak8=)
            client-secret: ENC(+gIL8lfla1khvDTeN5iNH2/JeovNx6F2)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: [ name, email, profile_image ]
          google:
            client-id: ENC(VYiQzc1m+kJCgU1Lwtx2Gdt8f56IAI57OmDvcHEFDrDaiAFCr6YisPWQu64SA7AdoT4HDFfZY2X3gq6DkHuPCWl6As221yUInaoYK0NSedFEU4CGtJPV5Q==)
            client-secret: ENC(BVhFhSSPaw/ETPglUuPriLl7sSwIIORBgF17DA4Ualmc+NvA1izqiscqdPwzTgfn)
            scope: [ profile, email ]
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


app:
  # cors
  cors:
    allowed-origins: 'http://localhost:3000'
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: '*'
    max-age: 3600
  # jwt secret key
  jwt:
    header: token
    issuer: prgrms
    tokenSecret: ENC(ue4i7O795mbBVZEgETESWrl9m5L/Mw+rhsYEejK1MfyGb3Hkatdfpnb2vTLy+bYC)
    tokenExpiry: 30000
    refreshTokenExpiry: 7776000000
  oauth:
    domain: "http://localhost:3000"
    sign-up-path: "/signup"
    sign-up-time: 30000
    login-path: "/main"

